### ISSUE TITLE
Add dark mode option 🌒

### ISSUE THREAD

**Issue by spsjvc** [novisadjs/blog#2]

**Comment by moonbyt3** [comment]
imam pull request za ovo, mogu li dobiti permisije da pushujem branch?

**Comment by spsjvc** [comment]
Hej, hvala ti puno što si odlučio da pomogneš!

Možeš na linku ispod pogledati kako da napraviš fork i pošalješ pull request na originalni repo:
https://guides.github.com/activities/forking/

**Comment by moonbyt3** [comment]
Nema na čemu. Ovo mi je inače prvi open source contribution u životu :D 
Evo ga preview https://deploy-preview-9--novisadjs-blog.netlify.com/

Pratiću ovaj repo pa ako budem znao uraditi koji issue rješavaću kad stignem. 
Slobodno budite detaljniji, bilo bi fino kad bi imali i dizajn neki :)
